services:
  - type: web
    name: telegram-bot
    env: python
    repo: https://github.com/sinharzs2k26/My-telegram-bot
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: telegram-bot
          property: port
    healthCheckPath: /health
    autoDeploy: true